### ISSUE TITLE
Can't send mail in production mode

### ISSUE THREAD

**Issue by hortongn** [uclibs/treatment_database#109]
When trying to reset a user's password in a production environment, the application encounters an error (trying to email the reset link).

Try this in a sandbox environment to replicate the problem.

**Comment by bsp3ars** [comment]
Log from Production.log

I, [2022-06-08T16:07:28.217795 #1347]  INFO -- : [a1346a11-25ce-49cb-b719-ba6c0d1e58d5]   Rendering devise/mailer/reset_password_instructions.html.erb
I, [2022-06-08T16:07:28.219238 #1347]  INFO -- : [a1346a11-25ce-49cb-b719-ba6c0d1e58d5]   Rendered devise/mailer/reset_password_instructions.html.erb (1.4ms)
D, [2022-06-08T16:07:28.219341 #1347] DEBUG -- : [a1346a11-25ce-49cb-b719-ba6c0d1e58d5] Devise::Mailer#reset_password_instructions: processed outbound mail in 8.7ms
I, [2022-06-08T16:07:28.219489 #1347]  INFO -- : [a1346a11-25ce-49cb-b719-ba6c0d1e58d5] Completed 500 Internal Server Error in 110ms (ActiveRecord: 3.0ms)
F, [2022-06-08T16:07:28.220163 #1347] FATAL -- : [a1346a11-25ce-49cb-b719-ba6c0d1e58d5]   
F, [2022-06-08T16:07:28.220203 #1347] FATAL -- : [a1346a11-25ce-49cb-b719-ba6c0d1e58d5] ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
F, [2022-06-08T16:07:28.220296 #1347] FATAL -- : [a1346a11-25ce-49cb-b719-ba6c0d1e58d5]     2: 
[a1346a11-25ce-49cb-b719-ba6c0d1e58d5]     3: <p>Someone has requested a link to change your password. You can do this through the link below.</p>
[a1346a11-25ce-49cb-b719-ba6c0d1e58d5]     4: 
[a1346a11-25ce-49cb-b719-ba6c0d1e58d5]     5: <p><%= link_to 'Change my password', edit_password_url(@resource, reset_password_token: @token) %></p>
[a1346a11-25ce-49cb-b719-ba6c0d1e58d5]     6: 
[a1346a11-25ce-49cb-b719-ba6c0d1e58d5]     7: <p>If you didn't request this, please ignore this email.</p>
[a1346a11-25ce-49cb-b719-ba6c0d1e58d5]     8: <p>Your password won't change until you access the link above and create a new one.</p>
F, [2022-06-08T16:07:28.220310 #1347] FATAL -- : [a1346a11-25ce-49cb-b719-ba6c0d1e58d5]   
F, [2022-06-08T16:07:28.220323 #1347] FATAL -- : [a1346a11-25ce-49cb-b719-ba6c0d1e58d5] app/views/devise/mailer/reset_password_instructions.html.erb:5:in `_app_views_devise_mailer_reset_password_instructions_html_erb___855164604834398409_51380'
