### ISSUE TITLE
Increase test coverage on existing code

### ISSUE THREAD

**Issue by hortongn** [uclibs/treatment_database#122]
We have some existing code that is not covered by tests.  Add tests for the following:

app/helpers/abbreviated_treatment_report_helper.rb
* missing tests for generate_sum_minutes

app/controllers/users_controller.rb
* missing tests for #show
* missing tests for create_user

**Comment by crowesn** [comment]
Looks like a test for create_user was added in the interim.

**Comment by hortongn** [comment]
@crowesn There's a test for create_user, but it doesn't cover all execution paths:

![Screen Shot 2021-09-27 at 1 42 14 PM](https://user-images.githubusercontent.com/5639859/134958638-4fe572c9-6197-40c4-a09b-8be534463ecb.png)
:

**Comment by scherztc** [comment]
Coverage report generated for RSpec to /Users/scherztc/Workspaces/treatment_database/coverage. 397 / 423 LOC (93.85%) covered.
[Coveralls] Outside the CI environment, not sending data.
[Coveralls] Some handy coverage stats:
  * app/channels/application_cable/channel.rb => 0%
  * app/channels/application_cable/connection.rb => 0%
  * app/controllers/abbreviated_treatment_reports_controller.rb => 100%
  * app/controllers/activity_controller.rb => 100%
  * app/controllers/application_controller.rb => 100%
  * app/controllers/con_tech_records_controller.rb => 100%
  * app/controllers/conservation_records_controller.rb => 93%
  * app/controllers/controlled_vocabularies_controller.rb => 100%
  * app/controllers/cost_return_reports_controller.rb => 100%
  * app/controllers/external_repair_records_controller.rb => 100%
  * app/controllers/front_controller.rb => 100%
  * app/controllers/in_house_repair_records_controller.rb => 100%
  * app/controllers/reports_controller.rb => 100%
  * app/controllers/search_controller.rb => 100%
  * app/controllers/treatment_reports_controller.rb => 100%
  * app/controllers/users/registrations_controller.rb => 0%
  * app/controllers/users_controller.rb => 100%
  * app/helpers/abbreviated_treatment_report_helper.rb => 93%
  * app/helpers/activity_helper.rb => 100%
  * app/helpers/application_helper.rb => 100%
  * app/helpers/con_tech_records_helper.rb => 100%
  * app/helpers/conservation_records_helper.rb => 100%
  * app/helpers/controlled_vocabularies_helper.rb => 100%
  * app/helpers/cost_return_report_helper.rb => 100%
  * app/helpers/external_repair_records_helper.rb => 100%
  * app/helpers/front_helper.rb => 100%
  * app/helpers/in_house_repair_records_helper.rb => 100%
  * app/helpers/search_helper.rb => 100%
  * app/helpers/treatment_reports_helper.rb => 100%
  * app/helpers/users_helper.rb => 100%
  * app/jobs/application_job.rb => 0%
  * app/mailers/application_mailer.rb => 0%
