### ISSUE TITLE
Build the docker containers in CircleCI

### ISSUE THREAD

**Issue by hortongn** [uclibs/treatment_database#128]
Our current CircleCI config just runs the app in CircleCI's ruby image.  We ant to make sure that CircleCI can also build our own Docker containers so we will know if there's a problem with our builds.

**Comment by bhanutejags** [comment]
## Related Links from Circle CI Documentation
### Building Docker Images
* [How to Build a Docker Image on CircleCI 2.0](https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/)
* [Running Docker Commands](https://circleci.com/docs/2.0/building-docker-images/)

### Testing/Validating Circle CI Jobs Locally
* [Using the CircleCI Local CLI](https://circleci.com/docs/2.0/local-cli/)
* [Local CI pipeline development](https://circleci.com/blog/local-pipeline-development/)
