### ISSUE TITLE
Explore hosting and deployment options in AWS

### ISSUE THREAD

**Issue by hortongn** [uclibs/treatment_database#129]
Explore the different ways we can host and deploy our Docker builds in AWS (ECS, ELB, EKS, etc.)

Generate pros and cons for the different options and create test deploys using the treatment application.

**Comment by hortongn** [comment]
@bhanutejags Passing this along in case it's helpful:
https://thoughtbot.com/blog/zero-downtime-rails-deployments-with-kubernetes

**Comment by bhanutejags** [comment]
# Notes
## Kubernetes
### Ingress Configurations
* [Ingress Path Matching](https://kubernetes.github.io/ingress-nginx/user-guide/ingress-path-matching/)
* [Ingress Configuration Through Annotations](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations)
* [Ingress examples])(https://kubernetes.github.io/ingress-nginx/examples/)
* [Ingress URL Rewrite](https://kubernetes.github.io/ingress-nginx/examples/rewrite/)
* [Using Nginx-Ingress as a Static Cache for Assets Inside Kubernetes](https://medium.com/@vdboor/using-nginx-ingress-as-a-static-cache-91bc27be04a1)

**Comment by bhanutejags** [comment]
### AWS Service Comparison
* All the below services have built-in integrations with AWS’s monitoring tools, like Amazon CloudWatch ([Amazon CloudWatch - Application and Infrastructure Monitoring](https://aws.amazon.com/cloudwatch/)).

#### ECS: Done
* The only thing platform-agnostic about this is the packaging.
	* Only the container image can be carried over to another platform
	* Everything else is proprietary.
* Does support a few deployment models, but less than those supported by EKS and ELS.
	* [Amazon ECS Deployment types - Amazon Elastic Container Service](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-types.html)
* Non-trivial to integrate with custom monitoring tools.
	- [ ] How to integrate 3rd party monitoring tools?

#### EKS
* Slightly Expensive
* Kubernetes Control Plane is charged, unlike on Azure.
	* $0.1 per hour -> $219 per month for 3 Kubernetes Clusters
		* Dev, QA, Prod
		* For only QA and Prod -> $146
	* This would be the minimum cost of maintaining three clusters, this does not include the cost of Worker Nodes, and Storage Costs etc.
* Supports complicated deployment strategies on top of Kubernetes
* Trivial to integrate with custom monitor tools of our choosing
* Can be run on on-premises, but require some amount of maintenance.

#### EB
* Service is free of charge, we are only charged for the EC2 instances and other resources.
* Some amount of Vendor Lock-in.
* Non-trivial to integrate with custom monitoring tools.
	* Can be done with custom AMI images
	* And `.ebextensions` customisation.
	- [x] How to integrate 3rd party monitoring tools?
	- Trivial to integrate custom monitoring tools without even going to custom images
		- We can simply write custom `.ebextensions` files for `promtail` or `prometheus`.
* Support many deployment models out of the box.
* Does not need a Docker image for deployments
	* The service prefers a zip archive of the code.
	* But can take in a Docker image if required.
