### ISSUE TITLE
Explore options for monitoring app health, uptime, and errors in AWS

### ISSUE THREAD

**Issue by hortongn** [uclibs/treatment_database#130]
Use the treatment application in AWS to test different ways to monitor uptime, monitor application health (database, web server, etc.), and monitor exceptions.

Would be nice to use the same tools to monitor app in AWS and IT@UC, but not required.

**Comment by bhanutejags** [comment]
## Integrating with 1st and 3rd party monitoring tools on AWS
* [Loki tutorial: How to set up Promtail on AWS EC2 to find and analyze your logs | Grafana Labs](https://grafana.com/blog/2020/07/13/loki-tutorial-how-to-set-up-promtail-on-aws-ec2-to-find-and-analyze-your-logs/)
* [Logging AWS Elastic Beanstalk with ELK | Logz.io](https://logz.io/blog/logging-aws-elastic-beanstalk-elk-stack/)
* [Integrating CloudWatch Logs with Grafana’s Loki | Novatec](https://www.novatec-gmbh.de/en/blog/integrating-cloudwatch-logs-with-grafanas-loki/)
* [Example: Using custom amazon CloudWatch metrics - AWS Elastic Beanstalk](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-cw.html)
* [Amazon CloudWatch Pricing – Amazon Web Services (AWS)](https://aws.amazon.com/cloudwatch/pricing/)
* [Amazon Managed Service for Grafana Pricing | Amazon Web Services](https://aws.amazon.com/grafana/pricing/)
* [What Is Amazon CloudWatch? - Amazon CloudWatch](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html)

## Links about Monitoring Tools
* [40+ Ruby on Rails Application Monitoring Tools 2020 - Hix on Rails](https://hixonrails.com/ruby-on-rails-tutorials/ruby-on-rails-application-monitoring/)
* [The OpenTracing project](https://opentracing.io)
* [OpenTelemetry](https://opentelemetry.io)
* [OpenTracing on Kubernetes —Get yer traces for free | by Matthew Lucas | OpenTracing | Medium](https://medium.com/opentracing/opentracing-on-kubernetes-get-yer-tracing-for-free-7a69cca03c8a)
* [GitHub - open-telemetry/opentelemetry-ruby: OpenTelemetry Ruby API & SDK, and related gems](https://github.com/open-telemetry/opentelemetry-ruby#quick-start)
* [Application Monitoring for Ruby on Rails, Elixir & Node.js | AppSignal APM](https://appsignal.com)

**Comment by bhanutejags** [comment]
## AWS CloudWatch
* [AWS re:Invent 2018: Monitor All Your Things: Amazon CloudWatch in Action with BBC (DEV302)](https://www.youtube.com/watch?v=uuBuc6OAcVY)
* [Building Dashboards on CloudWatch](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/CloudWatch-Dashboard-Body-Structure.html)

## AWS X-Ray
* [Getting Started with AWS X-Ray: Videos about X-Ray](https://aws.amazon.com/xray/getting-started/)
