### ISSUE TITLE
Set up ssh/console access to AWS-hosted app

### ISSUE THREAD

**Issue by hortongn** [uclibs/treatment_database#211]
The application is running in our QA AWS environment, but we have no way of interacting with the application files, logs, console, etc.

We need to configure a secure solution that will at least let us access the rails console prompt for the application.  Ideally we would want to be able to get to a command prompt within the Docker environment, but we need access to the rails console at a minimum.

**Comment by scherztc** [comment]
https://stackoverflow.com/questions/55845582/how-to-launch-a-rails-console-in-a-fargate-container

**Comment by scherztc** [comment]
https://github.com/mnc/rails-console-ecs

**Comment by hortongn** [comment]
@scherztc This could be relevant to your issue: https://engineering.loyaltylion.com/running-an-interactive-console-on-amazon-ecs-c692f321b14d

**Comment by scherztc** [comment]
The way to successfully do this is to use Amazone ECS Exec:
https://aws.amazon.com/blogs/containers/new-using-amazon-ecs-exec-access-your-containers-fargate-ec2/

Syntax: aws ecs execute-command  --region us-east-2  --cluster <cluster_name>  --task <task_id>  --container <container_name>  --command "rails c" --interactive

**Comment by scherztc** [comment]
https://github.com/uclibs/treatment_database/wiki/Running-Rails-Console-for-ECS
