### ISSUE TITLE
Integrate CircleCI with coveralls.io

### ISSUE THREAD

**Issue by hortongn** [uclibs/treatment_database#23]
Get coveralls.io working with circleci builds.

Additions needed to .circleci/config.yml
* https://github.com/uclibs/ucrate/blob/develop/.circleci/config.yml#L46
* https://github.com/uclibs/ucrate/blob/develop/.circleci/config.yml#L84-L86

Create .coveralls.yml
* https://github.com/uclibs/ucrate/blob/2e36b547ef7f1423dc990474fce6f470925709ce/.coveralls.yml

Get the repo token from https://coveralls.io/github/uclibs/treatment_database and add it to the circleci environment variable settings

Set up github to require passing coveralls checks for PR merges

**Comment by chuckgreenman** [comment]
Consider CircleCI's internal coverage tool.
