### ISSUE TITLE
Create rake task to create records from CSV input

### ISSUE THREAD

**Issue by crowesn** [uclibs/treatment_database#256]
Rake task to take csv input and build records. 

Related: #44 

* Start with conservation record, use csv file from Teams folder
* Retain `Database_ID` from access database
* Ignore created and update dates

**Comment by crowesn** [comment]
https://github.com/uclibs/ucrate/commit/3964c06c23b5b1469364f08e6f3b90d73f12f367

**Comment by crowesn** [comment]
1. Remove record validations from models
2. Convert `ConservationRecord.digitization` from 1/0 to boolean
3. Create db migration to fix type in https://github.com/uclibs/treatment_database/blob/qa/db/schema.rb#L31

**Comment by scherztc** [comment]
Next step is to get the Controlled Vocabularies related to the Conservation Records.

Couldn't find ControlledVocabulary with 'id'=1

**Comment by crowesn** [comment]
See https://github.com/uclibs/treatment_database/issues/259 for controlled vocabulary functionality.
