### ISSUE TITLE
Migrate in-house and external repair records from CSV

### ISSUE THREAD

**Issue by hortongn** [uclibs/treatment_database#257]
Depends on #256 

This task should be run after the Conservation Records have been created/migrated.

Using the fields below from the Conservation Data.csv file, create an InHouseRepairRecord for each existing record in the CSV and link it to its associated `conservation_record_id`:
```
Type In-house Repair,Preformed In-house Repair,Time In-house Repair,Staff Code,
Type In-house Repair 2,Preformed In-house Repair 2,Staff Code2,Time In-house Repair 2,
Type In-house Repair 3,Preformed In-house Repair 3,Staff Code3,Time In-house Repair 3,
Type In-house Repair other,Preformed In-house Repair other,Staff Codes other,Time In-house Repair other
```

Using the fields below from the Conservation Data.csv file, create an ExternalRepairRecord for each existing record in the CSV and link it to its associated `conservation_record_id`:
```
Type Vendor Repair,Preformed by Vendor,
Type Vendor Repair 2,Preformed by Vendor 2,
Type Vendor Repair 3,Preformed by Vendor 3,
Type Vendor Repair other,Preformed by Vendor other
```

**Comment by crowesn** [comment]
In House Repairs need a `:performed_by_user_id`, which should correspond to an application user account. 
1. Do we want to load a csv with all staff accounts? Is this a file we want to persist the repo? Privacy issues?
2. The data for staff needs to be cleaned up, name types and inconsistencies are plentiful
    - There is a staff code field in the input data, we could potentially use this to key to application user accounts but we'd need to create a file/index

**Comment by crowesn** [comment]
See https://github.com/uclibs/treatment_database/issues/275.

Lookup user account by some combination of first name or last name. If account not found, assign generic user account.
