### ISSUE TITLE
Add ControlledVocabulary to ConservationRecords rake task

### ISSUE THREAD

**Issue by crowesn** [uclibs/treatment_database#259]
Could be a stand alone rake task for loading controlled vocab discretely or as just loading controlled vocab as part of ConservationRecord load.

Vocab types:
* contract_conservators
* repair_type
* housing
* departments

**Comment by crowesn** [comment]
@scherztc 

The data points for `Type In House Repair` are integers--looks like they could be keys. Is there a table for in-house-repair-type?

![Screen Shot 2022-01-12 at 3 17 57 PM](https://user-images.githubusercontent.com/1069588/149215340-8fe1b93f-c056-4fd7-b628-79d5fd5fd324.png)

**Comment by hortongn** [comment]
@crowesn @scherztc I was able to find a Types of Repairs table in the Access database.  I exported it to a .csv file in our Teams treatment channel files (Migration folder).
