### ISSUE TITLE
Resolve character encoding issues

### ISSUE THREAD

**Issue by hortongn** [uclibs/treatment_database#274]
In the records we've migrated over so far there are lots of character encoding issues from either the Access export or the way we're importing the content.  We need to figure out the source of the problem and resolve it in our migration strategy.

**Comment by crowesn** [comment]
Tested Excel export from Access db and noted that we need to ensure correct format when saving Excel > CSV.
*It's critical that we select the proper format when saving the CSV file.*

In **Excel**, save as:
<img width="358" alt="Screen Shot 2022-04-14 at 1 37 27 PM" src="https://user-images.githubusercontent.com/1069588/163449592-6b964e1b-7281-4dec-8b1f-3abbd572e9d6.png">

In **Libreoffice**, save as:
![Screen Shot 2022-04-14 at 1 23 33 PM](https://user-images.githubusercontent.com/1069588/163449936-e9b6702c-8aef-4af8-90c9-e8434a0509f8.png)

![Screen Shot 2022-04-14 at 1 26 42 PM](https://user-images.githubusercontent.com/1069588/163449564-b2adf207-1b46-42ff-9aa0-b0f08df02fc2.png)
