### ISSUE TITLE
Verify the migration

### ISSUE THREAD

**Issue by hortongn** [uclibs/treatment_database#284]
Complete the steps below.  If problems are found, create new issues for them and link to them in the comments of this issue.

1. Verify the number of records.  There should be 1947 conservation records total.

1. Check all fields
    * create a record in the Access database that has all fields filled in
    * create a record in the application that has all fields filled in
    * Export the Access data and run the migration
    * Bring up both records side-by-side and compare for differences

1. Spot check 20 random records between the Access database and the app
    * Create new issues for any differences found
    * Keep track of which records you compared

**Comment by scherztc** [comment]
1.  Found 2583 Records.
2. Created an Uber record in the Application, but did not run a migration against the database.
3. Attempted to spot check record, but search failed.

**Comment by scherztc** [comment]
Questions : 
What is the difference between Description and Condition on Treatment Report?
What is Text Block?
Show we be able to Attach files?  What is attachment?
Conservation Report  has two Download ?
Use $ label on cost fields.
Wow do I see a save button (Read Only)
Search is broke

**Comment by scherztc** [comment]
2583 PIDS
257 Records

**Comment by scherztc** [comment]
I was able to add an Uber Record to the .csv and import it into my local environment.  Even after filling out all the fields in the .csv, I still didn't see any data populate the Treatment Report.

<img width="423" alt="Screen Shot 2022-07-01 at 12 49 43 PM" src="https://user-images.githubusercontent.com/5084562/176937262-112ce112-cefd-4b14-b156-feeb253ff22f.png">
<img width="423" alt="Screen Shot 2022-07-01 at 12 49 43 PM" src="https://user-images.githubusercontent.com/5084562/176937262-112ce112-cefd-4b14-b156-feeb253ff22f.png">

**Comment by scherztc** [comment]
https://libappstest.libraries.uc.edu/treatment_database/conservation_records/606
