### ISSUE TITLE
Enhance Staff Code

### ISSUE THREAD

**Issue by scherztc** [uclibs/treatment_database#298]
V= volunteer (0 points)
T= technician (10 points)
S = student (5 points)
C = conservator (20 points)
A = assistant conservator  (15 points)
 
Our goal is to have an equal output per institution at the end of each quarter.  Piece count lets us know what services are most requested at each institution, but it doesn’t touch on the true “cost” of treating each item. The cost of having the conservator work on a rare book over many hours is not the same investment as a student repairing a general circulating item in a relatively short period of time.  To illuminate the true cost we use a weighted point system with a multiplication factor.  For example:
 
Rare book (conservator):
70 minutes X 20 (the “factor”) / 60 minutes = 23 pts
 
General circulating (student):
60 minutes x 4 (the “factor”) / 60 minutes = 4 pts

**Comment by hortongn** [comment]
Let's bring it up to Preservation Services when we demo for them to see if and what they need for a staff codes report.
