### ISSUE TITLE
Add the Ability to Assign Conservators and Technicians to a Conservation Record

### ISSUE THREAD

**Issue by chuckgreenman** [uclibs/treatment_database#30]
A list of technicians and conservators that work on a treatment need to be tracked.  I'm envisioning this being a modal that allows the user to pick users from a dropdown list, and be removed using a button much like in house and external treatment records are handled now.

**Comment by hortongn** [comment]
@harithavytla I think this may be the best next issue for you to work on.  We can talk about it on Thursday.

**Comment by hortongn** [comment]
@harithavytla https://github.com/uclibs/treatment_database/pull/15

**Comment by hortongn** [comment]
<img width="1440" alt="Screen Shot 2020-10-08 at 1 20 13 PM (2)" src="https://user-images.githubusercontent.com/5639859/95492491-257b8480-0969-11eb-9b02-3c6dbe01c9e5.png">
