### ISSUE TITLE
PDFkit error on libappstest

### ISSUE THREAD

**Issue by crowesn** [uclibs/treatment_database#310]
```
I, [2022-06-08T16:00:40.691314 #1347] INFO -- : [6673b991-7e76-4e85-bdad-403c90a8add6] Completed 500 Internal Server Error in 247ms (ActiveRecord: 4.4ms)
F, [2022-06-08T16:00:40.691768 #1347] FATAL -- : [6673b991-7e76-4e85-bdad-403c90a8add6]
F, [2022-06-08T16:00:40.691798 #1347] FATAL -- : [6673b991-7e76-4e85-bdad-403c90a8add6] PDFKit::ImproperWkhtmltopdfExitStatus (Command failed (exitstatus=1): /opt/webapps/treatment_databas
e/shared/vendor/bundle/ruby/2.7.0/bin/wkhtmltopdf --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 --print-
media-type --dpi 96 --footer-right Page\ \[page\] --footer-font-size 8 --footer-left \[date\] - -):
F, [2022-06-08T16:00:40.691812 #1347] FATAL -- : [6673b991-7e76-4e85-bdad-403c90a8add6]
F, [2022-06-08T16:00:40.691849 #1347] FATAL -- : [6673b991-7e76-4e85-bdad-403c90a8add6] app/controllers/conservation_records_controller.rb:99:in `build_pdf'
```

**Comment by crowesn** [comment]
Resolve with 
`gem install executable_hooks`
`gem install wkhtmltopdf-binary`
```
ln -s /opt/webapps/treatment_database/shared/vendor/bundle/ruby/2.7.0/gems/wkhtmltopdf-binary-0.12.6.5/bin/wkhtmltopdf_centos_8_amd64.gz/opt/webapps/treatment_database/shared/vendor/bundle/ruby/2.7.0/gems/wkhtmltopdf-binary-0.12.6.5/bin/wkhtmltopdf_ol_8.6_amd64.gz```

**Comment by hortongn** [comment]
@crowesn Nice job.  I do see that wkhtmltopdf-binary is already in our Gemfile.  Are you sure it was necessary for you to install that gem again?  But maybe our bundle install into the vendor directory isn't where it likes to live?

Also, that symlink looks brittle like it would break if we change our ruby version or the wkhtmltopdf-binary version.  So we need to come up with a way to stabilize it or something.

**Comment by crowesn** [comment]
It’s possible that I was outside of the application directory for some of my testing, which could be why I needed to install wkhtmltopdf-binary gem. The gem pulls env values and interpolates them into a string to point to the binary, based on os and processor. In our case, it’s pulling “ol” for open linux from our system even though we are able to use the centos binary. I can probably express this better verbally.

**Comment by crowesn** [comment]
@hortongn Can we close this issue since we've crafted a solution?

**Comment by crowesn** [comment]
Reviewer reported broken pdf download on libappstest:
> Was not able to download the abbreviated treatment report for i37045015.

Log showed the app was looking for a 8.7 version of wkhtmltopdf, probably bumped during updates.
Fixed by adding new symlink to bin dir but this reiterates how brittle our fix is.

```bash
ln -s /opt/webapps/treatment_database/shared/vendor/bundle/ruby/2.7.0/gems/wkhtmltopdf-binary-0.12.6.5/bin/wkhtmltopdf_centos_8_amd64.gz /opt/webapps/treatment_database/shared/vendor/bundle/ruby/2.7.0/gems/wkhtmltopdf-binary-0.12.6.5/bin/wkhtmltopdf_ol_8.7_amd64.gz
```

**Comment by crowesn** [comment]
https://github.com/zakird/wkhtmltopdf_binary_gem/pull/155
