### ISSUE TITLE
Forgot Password broken on Login Page

### ISSUE THREAD

**Issue by scherztc** [uclibs/treatment_database#329]
https://libappstest.libraries.uc.edu/treatment_database/users/sign_in

User gets : 
  The application encountered an error

Large UC Logo

**Comment by hortongn** [comment]
Problem was caused by missing variables in the .env.production files on libappstest.  I added to /opt/webapps/treatment_database/static/.env.production and copied to   /opt/webapps/treatment_database/current/.env.production and then restarted the app.  Working now.
