### ISSUE TITLE
Vendor list for external repairs is not displaying on libappstest

### ISSUE THREAD

**Issue by hortongn** [uclibs/treatment_database#340]
On our QA instance at https://libappstest.libraries.uc.edu/treatment_database, when on the /conservation_records/id page and the user clicks the "Add External Repair" button, the pop up modal has a "repaired by" field with a blank vendor list.

We need to populate the vendor list.

I also received an error after saving the repair record with a blank vendor.  The application should not allow users to save repair records if required fields are empty.

**Comment by crowesn** [comment]
This bug extends to In-house repairs as well.
