### ISSUE TITLE
Implement SSO login

### ISSUE THREAD

**Issue by crowesn** [uclibs/treatment_database#407]
Using shibboleth, implement SSO for the Treatment Database.

Example PR from ucrate: https://github.com/uclibs/ucrate/pull/1162
* Pull the tests over and get them running (failing)
* Pull over the code to turn the tests green

Need to discuss how this implementation should differ from ucrate

**Comment by Janell-Huyck** [comment]
## Proposed sub-issues:
- make feature branch -Janell
- move the tests over from [the demo PR](https://ituc.service-now.com/kb? -Janell id=kb_article_view&sysparm_article=KB0011603&sys_kb_id=14fca971972bcd904f51f7afe153aff0)
- put in a ticket with IDM with a service request form to request SSO service to IDM
- check that we have endpoints and what we need for metadata and entity ID to give to IDM
- write how-to troubleshoot for Holly - how to check that the user's email matches the SSO email
- get contact information for one Public Library person to ask them to test the login with their SSO
- add gems and run bundle install
- review the demo PR and break down the code into discrete sections -Janell
- set up a development login environment vs qa vs test
- find out if we had to make server changes for scholar's SSO?  We don't think there's anything on Libapps that's using SSO. - Lisa
- review using OmniAuth -Lisa
- next meeting is next Wed May 1 at 12:30 PM

**Comment by Janell-Huyck** [comment]
Pre-work PR:  clean up the "registrations" controller and view.  It's not being used and not planned to be used in the future.  Include test clean-up.  Ensure users can still edit their display names, using the User controller methods.
