### ISSUE TITLE
Install Times New Roman font package on libappstest, libapps

### ISSUE THREAD

**Issue by crowesn** [uclibs/treatment_database#441]
Related: #435 

QA deploy to libappstest.libraries.uc.edu does not include Times New Roman font in PDFs, defaulting to a sans-serif font. We'll want to make sure Times is installed on QA and Prod environments.

**Comment by crowesn** [comment]
I suppose I could do a sample with the open font and see if that causes problems when they try to edit the document.

**Comment by crowesn** [comment]
> Sean, libappstest already has a font family installed called Nimbus Roman that is just like Times New Roman.  
> You may want to deploy a test branch with your PDF view set to use "Nimbus Roman" and see if that works.

**Comment by Janell-Huyck** [comment]
Moved to Jira
