### ISSUE TITLE
Provision hosting environment for treatment application

### ISSUE THREAD

**Issue by hortongn** [uclibs/treatment_database#5]
Get the application running on AWS 
- [x] Deploy application is development mode
- [x] Provide ssh command line access to the application
- [x] Connect to an external database

For Production mode
- [x] Decide on a web server to use (Nginx, Apache, etc.)
- [ ] Domain name and certificate

**Comment by chuckgreenman** [comment]
After meeting with Dennis we have decided to host this on Lucy while Demoing it.  Here are some configuration details for setting up the application in a server environment like Lucy.

Install RVM
rvm use "ruby-2.5.1"
Clone the repo to your home folder
gem install bundler
bundle install
yum install nodejs (Rails needs a javascript runtime to execute database migrations.)
Determine the IP address of the server with `ip addr`
If not already in place create a firewall rule for port 3000
Start up the rails server using `rails server --bind=0.0.0.0`

**Comment by hortongn** [comment]
We can try running in production mode under Nginx/Puma.

Before setting things up on the production server, we should try to get another instance of the app running on Lucy in production mode under Nginx/Puma and using MySQL as the DB.  

We want to work out as much of the config and kinks as possible on Lucy before attempting it on the production server.

Example config:
https://www.digitalocean.com/community/tutorials/how-to-deploy-a-rails-app-with-puma-and-nginx-on-ubuntu-14-04
