### ISSUE TITLE
Admin user can enable and disable users

### ISSUE THREAD

**Issue by crowesn** [uclibs/treatment_database#57]
## Description

Only the preservation folks should have access to the content in the app.
So admins will need the ability to disable a user from logging in if that person leaves (either temporarily or permanently).

e.g. a student has an account and leaves the department for a semester and then returns.  Admin should be able to disable their account from logging in and then be able to re-enable it later.
10:43

I suggest the admin can see a checkbox on the user’s edit page when they can disable them.

Related https://github.com/uclibs/treatment_database/issues/10

**Comment by chuckgreenman** [comment]
@crowesn This looks good, shouldn't we make new users inactive by default though?  If someone leaves the department and their account is deactivated they could just create a new account with a different email address.

**Comment by hortongn** [comment]
I think the plan is to disable self-signup when this goes in to production.  So if the admin is creating a new user, we can assume they should be active by default.

**Comment by chuckgreenman** [comment]
Ah, gotcha, sounds like a plan.
