### ISSUE TITLE
Change PDF Reports to Match Current Report

### ISSUE THREAD

**Issue by chuckgreenman** [uclibs/treatment_database#74]
Our current implementation of PDF reports looks fairly different from their access reports.

- Check Conservation Report, Treatment Report and Abbreviated Treatment Report to ensure we get it right everywhere we are building a PDF.

**Comment by hortongn** [comment]
@harithavytla I've emailed you examples of what the reports should look like

**Comment by harithavytla** [comment]
1) Treatment ID field is missing in our schema which was displayed in the treatment reports pdf.
2) Should the Conservators and Technicians field display the ones' which will be added by the admin in the "Show conservation records page"?
