### ISSUE TITLE
See Conservation Records in a Spreadsheet like format

### ISSUE THREAD

**Issue by chuckgreenman** [uclibs/treatment_database#79]
Currently, the access database allows users to click on the Conservation Data table and view all of the information in a spreadsheet like format.  We want to replicate this kind of functionality and allow for viewing and exporting data in a spreadsheet format.

**Comment by crowesn** [comment]
This was requested again in the context of the reports page:
```
Can we export lists of items being returned? (Didn’t see this function). 
All the items with the same return date, is it possible to export the data to an excel format? 
```

**Comment by crowesn** [comment]
https://github.com/uclibs/application_portfolio/pull/155/files#diff-6558e486324e84a0b6943099b58a654441b3b2ab9ef310f6d31be453dcb3e5d8
