### ISSUE TITLE
Set up Paper Trail

### ISSUE THREAD

**Issue by chuckgreenman** [uclibs/treatment_database#9]
paper_trail is a gem that can be configured to track changes by defining events to keep track of.

- [x] Track creation and updates to Conservation and Treatment Records

- [x] Track the creation and updates to In-House and Outside repair records.

- [x] Create a page where admins or standard users can view the log.

- [x] Add link to activity#index in site header for admins only (next to "Users" link)

- [x] On the activity#index page, for repair records include the title of the conservation record

- [x] Remove the "Revert to This Version" button on the activity#show page

- [x] Include edits to the Cost and Return Information section on activity#index

- [x] Add pagination to the activity#index page (50 records per page)

- [x] Support deleted records on activity#index

**Comment by crowesn** [comment]
Is this an administrative task, perhaps that could included in a dashboard, or should it show for each record to a standard user?
